### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by RIAstar** [nickvdyck/gulp-jspm-assets#1]
Yeah, I know. But some of us are forced to actually get stuff developed on Windows :(

The problem seems to be with the paths:
if I have a glob `src/myFile.png`, that becomes an absolute path somewhere down the road that looks like `\\c:\path\to\project\src\myFile.png`

**Comment by RIAstar** [comment]
Fixed the issue, but in doing that, I noticed that the build also doesn't work on Windows (even in Git Bash, which is a unix-like environment).
The problem is in the `postbuild` command: `cp -p $(find .tmp/src -type f) lib` crashes.

**Comment by vandycknick** [comment]
Hm yeah never made this one windows friendly, sr about that. I got a windows box ready so I'll have a look at your pr tonight.

**Comment by vandycknick** [comment]
PR merged and released as version 1.1.2. I'm not sure if git bash for windows implements all the bash and coreutils features. But i'll have a look to replace it by npm modules. I need to simplify the build anyways. If you like to take a stab at this then be my guest. 😄

**Comment by vandycknick** [comment]
So version 1.1.3. is out there, give it a spin and let me know if this fixes your problems.

**Comment by RIAstar** [comment]
Damn! Just noticed I introduced a booboo for Linux now.
Sorry about that :(
All tests were passing so I assumed I was safe. My bad.

On Linux you need a leading forward slash for an absolute path, whereas on Windows you don't (because it starts with a drive letter).
Could be fixed by `filePath.replace(this.protocolRE, process.platform === 'win32' ? '' : '/');`
Want me to create another PR for that? Not a good idea to amend the previous commit since you already made a release...

**Comment by RIAstar** [comment]
Just saw you fixed it already.
Cool! Sorry again.
I'll give it a spin tomorrow on my Windows box.

**Comment by vandycknick** [comment]
No worries, just wondering if your approach isn't better than what I came up with. Testing didn't pick this up because it relies on a mocked jspm version. But I'm planning to add a test case for this path issue to make sure it's not regressing on windows or unix.

**Comment by RIAstar** [comment]
Myea, I don't like the OS sniffing that much either.
I tried NodeJS' [url.parse()](https://nodejs.org/dist/latest-v5.x/docs/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost) as well, but it resulted in a `pathname` without a leading slash just the same.

**Comment by RIAstar** [comment]
I'm afraid your change to the regex still doesn't work on Windows :(
Because it's _3_ forward slashes and you want to remove all of them.

Input for `cleanFilePath()`: `file:///c:/somePath`
Output: `/c:/somePath`
Expected: `c:/somePath`

**Comment by vandycknick** [comment]
Sr about the mess. I ended up doing another release with your suggested platform check. Just tested my unix and windows box, v1.1.4 is working fine on both of them. I'm going to have to investigate the file uri schema and find a proper solution for this problem. But thanks for your patience.

**Comment by RIAstar** [comment]
Don't worry. I have a private npm for that ;)
Not everyone is as quick to respond as you are...
Thanks

**Comment by RIAstar** [comment]
Verified on my Windows workstation and Linux/Jenkins box.

I'll leave the issue open since you indicated that you wanted to investigate a little more.

It would seem the URI scheme is actually pretty consistent across OS's:
*nix:

```
file://localhost/etc/fstab
file:///etc/fstab
```

windows:

```
file://localhost/c:/somePath
file:///c:/somePath
```

The difference lies in how you have to transform it into a valid absolute path:
in *nix you want to keep that leading forward slash, whereas in Windows you need to get rid of it...
